# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-18 06:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='latlng',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
